DorDam/Controllers/userAuthenticationController.cs
using DorDam_ENTITY;
using DorDam_SERVICE;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DorDam.Controllers
{
    public class userAuthenticationController : Controller
    {
        //
        // GET: /userAuthentication/
        iLog_in_Service log = Service_Center.GetLog_in_Service();
        public ActionResult Index()
        {
            if (Session["userName"]==null)
            {
                @ViewBag.ErrorMsg = Session["errormsg"];
                return View();
            }
            else
            {                
                return RedirectToAction("accessDenied");
            }
        }

        public ActionResult accessDenied()
        {
            ViewBag.userName = Session["userName"];
            ViewBag.logged = Session["LoggedIN"];
            return View();
        }

        public ActionResult checkLogin()
        {
            string username = Request.Form["username"];
            string password = Request.Form["pass"];

            Log_in logIN = new Log_in();

            if(log.Get(username,password)==null)
            {
                Session["errormsg"] = "Log In Falied. Check UserName Or Password";
                return RedirectToAction("Index");
                //return View();
            }
            else
            {
                if(username == "admin")
                {
                    return RedirectToAction("Index","Admin");
                }
                else
                {
                    FormsAuthentication.SetAuthCookie(username, true);
                    Session["userName"] = username;
                    Session["LoggedIN"] = true;
                    return RedirectToAction("Index", "Home");
                }                
            } 
        }

        public ActionResult LogOut()
        {
            Session.Clear();

            FormsAuthentication.SignOut();

            return RedirectToAction("Index","Home");
        }
    }
}

DorDam/Views/userAuthentication/Index.cshtml
@{
    Layout = "~/Views/Common/Common_View.cshtml";
}

<div class="container">
@using (Html.BeginForm("checkLogin", "userAuthentication"))
{ 
    <div class="form-signin">
        <h2 class="form-signin-heading"></h2>
        <label for="inputEmail" class="sr-only">User Name</label>
        <input type="text" id="inputUsername" name="username" class="form-control" placeholder="User Name" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="pass" class="form-control" placeholder="Password" required><br />
        <div class="checkbox">
                <strong>@ViewBag.ErrorMsg</strong>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </div>
}
    <br />
        <div class="col-sm-3"></div>
        <div class="col-sm-6">&nbsp; &nbsp;
            <label>
                Don't you have any Account ? &nbsp; &nbsp; Press <strong>
                    <a href="/UserProfile/Create"> <i class="fa fa-sign-in" aria-hidden="true"></i>Sign Up</a>
                </strong> to Creat an Account.
            </label>
        </div>
</div>

    @section Title{
        DorDam
    }


    @section header{
        Sign in
    }

DorDam/Views/userAuthentication/accessDenied.cshtml
@{
    ViewBag.Title = "accessDenied";
    Layout = "~/Views/Common/Common_View.cshtml";
}
<h1 align="center">Access Denied</h1>



@section Title{
    Access Denied
}


@section header{
    Error :  401
}