DorDam/Controllers/SeclectProductController.cs
using DorDam_ENTITY;
using DorDam_SERVICE;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DorDam.Controllers
{
    public class SeclectProductController : Controller
    {
        // GET: /Category/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SelectItem(int productID)
        {
            ViewBag.userName = Session["userName"];
            ViewBag.logged = Session["LoggedIN"];
            //ViewBag.id = productID;
            iProduct_Service product = Service_Center.GetProduct_Service();

            int catid = product.Get(productID).Category_ID;
            int subcatid = product.Get(productID).Sub_Category_ID;

            iCategory_Service cat = Service_Center.GetCategory_Service();
            iSub_Category_Service sub = Service_Center.GetSub_Category_Service();

            ViewBag.categoryName = cat.Get(catid).Category_Name;
            ViewBag.subcategoryName = sub.Get(subcatid).Sub_Category_Name;
            ViewBag.productPicture = Url.Content(product.Get(productID).Product_Picture);

            Session["SelectItemDetails"] = productID;

            if (product.Get(productID).Product_Quantity > 5)
            {
                ViewBag.productStatus = "In Stock";
            }
            else
            {
                ViewBag.productStatus = "Out of Stock";
            }

            return View(product.Get(productID));
        }

        [HttpPost]
        public ActionResult AddingToCart() 
        {
            if (Convert.ToBoolean(Session["LoggedIN"]) == true)
            {
                iCart_Service cartService = Service_Center.GetCart_Service();
                iProduct_Service product = Service_Center.GetProduct_Service();
                iCategory_Service cat = Service_Center.GetCategory_Service();
                iSub_Category_Service sub = Service_Center.GetSub_Category_Service();

                int productID = Convert.ToInt32(Session["SelectItemDetails"]);
                int catid = product.Get(productID).Category_ID;
                int subcatid = product.Get(productID).Sub_Category_ID;

                Cart cart = new Cart();

                cart.ProductID = productID;
                cart.ProductName = product.Get(productID).Product_Name;
                cart.ProductCategory = cat.Get(catid).Category_Name;
                cart.ProductSubCategory = sub.Get(subcatid).Sub_Category_Name;
                cart.ProductPicture = product.Get(productID).Product_Picture;
                cart.ProductPrice = product.Get(productID).Product_Price;
                cart.BuyingQuantity = Convert.ToInt32(Request.Form["quantityItem"]);
                cart.Username = Session["userName"].ToString();

                int i = cartService.Insert(cart);

                if (i == 1)
                {
                    return RedirectToAction("Index", "Cart");
                }

                else
                {
                    return RedirectToAction("Index", "Home");
                }            
            }
            else
            {
                return RedirectToAction("Index", "userAuthentication");
            }

        }

        public void Edit() 
        {
            
        }

    }
}

DorDam/Views/SeclectProduct/SelectItem.cshtml
@model DorDam_ENTITY.Product

@{
    ViewBag.Title = "SelectIedItem";
    Layout = "~/Views/Common/Common_View.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-4" style="background-color:lavenderblush;">
            <br />
            <img src="@ViewBag.productPicture" id="myImg" class="img-rounded" alt="@Html.DisplayFor(model => model.Product_Name)" width="350" height="350"> 
            <div id="myModal" class="modal">
                <span class="close">&times;</span>
                <img class="modal-content" id="img01">
                <div id="caption"></div>
            </div>

        </div>
        <div class="col-sm-4" style="background-color:lavender;"><br />
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <td><dl>
                                <dt class="text-success">Product Name</dt>
                            </dl>    
                         </td>
                        <td>@Html.DisplayFor(model => model.Product_Name)</td>
                    </tr>
                    <tr>
                        <td>
                            <dl>
                                <dt class="text-success">Product Category</dt>
                            </dl>
                        </td>
                        <td>@ViewBag.categoryName</td>
                    </tr>
                    <tr>
                        <td>
                            <dl>
                                <dt class="text-success">Product Section</dt>
                            </dl>
                        </td>
                        <td>@ViewBag.subcategoryName</td>
                    </tr>
                    <tr>
                        <td>
                            <dl>
                                <dt class="text-success">Product Price</dt>
                            </dl>
                        </td>
                        <td>@Html.DisplayFor(model => model.Product_Price)</td>
                    </tr>
                    <tr>
                        <td>
                            <dl>
                                <dt class="text-success">Product About</dt>
                            </dl>
                        </td>
                        <td>@Html.DisplayFor(model => model.Product_About)</td>
                    </tr>
                    <tr>
                        <td>
                            <dl>
                                <dt class="text-success">Product Availability</dt>
                            </dl>
                        </td>
                        <td>@ViewBag.productStatus</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<br /> <br /> 
<hr />
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-2" style="background-color:lavenderblush;"></div>  
        <div class="col-sm-2">
            <dl>
                <dt class="text-capitalize">Buying Quantity</dt>
            </dl>  
        </div>
        @using (Html.BeginForm("AddingToCart","SeclectProduct"))
            {    
            <div class="col-sm-2" style="background-color:lavenderblush;">                         
                <div class="form-group">
                    <select class="form-control" id="quanity" name="quantityItem">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-primary" name="addingCart" value="Add to Cart">
            </div>
            }
        <div class="col-sm-2" style="background-color:lavenderblush;"></div>
    </div>
</div>

<script>

    var modal = document.getElementById('myModal');

    var img = document.getElementById('myImg');
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    img.onclick = function () {
        modal.style.display = "block";
        modalImg.src = this.src;
        captionText.innerHTML = this.alt;
    }

    var span = document.getElementsByClassName("close")[0];

    span.onclick = function () {
        modal.style.display = "none";
    }
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>


@section Title{
    Product Details
}


@section header{
    Product Description
}